### ISSUE TITLE
TAKLinuxService: a demon for linux not starting

### ISSUE THREAD

**Issue by nconder** [Tapawingo/FreeTakServer#45]
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-99-generic x86_64)

running:
root@#####:/TAKlib/TAKfreeServer/TAKLinuxService# python3 beginServerFromLinux.py -p 8087

output:
nohup: appending output to 'nohup.out'

No process ever starts. Am I missing something? I tried with and without port switch "-p" with and got the same results.

This works good though.. python3 /TAKlib/TAKfreeServer/server.py -p 8087

**Comment by naman108** [comment]
could you post your constants

**Comment by nconder** [comment]
It works as expected now that I found out about adding server ip to constants.py #47 
Documentation should be added about constants.py and run.sh
