### ISSUE TITLE
No such file or directory: '/logs/FTS_debug.log'

### ISSUE THREAD

**Issue by nconder** [Tapawingo/FreeTakServer#46]
After recent pull I now get No such file or directory: '/logs/FTS_debug.log'. The new folder needs to be added to the repo or the application fails to start. 

Ruining:
python3 /TAKlib/TAKfreeServer/server.py -p 8087

Output:
Traceback (most recent call last):
  File "/TAKlib/TAKfreeServer/server.py", line 47, in <module>
    logger.addHandler(newHandler(const.DEBUGLOG, logging.DEBUG, log_format))
  File "/TAKlib/TAKfreeServer/server.py", line 37, in newHandler
    backupCount=const.BACKUPCOUNT
  File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/logs/FTS_debug.log'

**Comment by a-f-G-U-C** [comment]
`mkdir logs` in the TAKfreeServer directory.

**Comment by a-f-G-U-C** [comment]
Also, I just noticed that the missing `logs` directory is created by `httpServer.py` so the problem is probably avoided by executing the `run.py` wrapper to start the software components (`server` and `httpServer`) instead of running them individually. :)

**Comment by nconder** [comment]
> Also, I just noticed that the missing `logs` directory is created by `httpServer.py` so the problem is probably avoided by executing the `run.py` wrapper to start the software components (`server` and `httpServer`) instead of running them individually. :)

Yes, both mkdir and run.py work. I was not aware of run.py or missed this in the docs if it was referenced some place. Thanks!
