### ISSUE TITLE
Clarify Python 3.6+ minimum requirement

### ISSUE THREAD

**Issue by a-f-G-U-C** [Tapawingo/FreeTakServer#48]
The README file states that FTS is Python3 software, however due to extensive use of **f-strings** (introduced in 3.6) it is incompatible with any Python3 version pre 3.6. 

Currently, attempting to run the software in Python 3.4 fails ugly:
```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    import httpServer
  File "/home/takserv/FreeTakServer-master/TAKfreeServer/httpServer.py", line 31
    print(f"Creating directory at {const.LOGDIRECTORY}")
                                                      ^
SyntaxError: invalid syntax
```

I suggest this should be indicated in the README, as well as checked and reported elegantly at runtime.

**Comment by brothercorvo** [comment]
in 0.8 included in the Pip requirement packaging

**Comment by brothercorvo** [comment]
we have updated the readme to reflect that
