### ISSUE TITLE
TypeError: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by cherijakewell** [Tapawingo/FreeTakServer#49]
Currently getting the error **'TypeError: an integer is required (got type NoneType)'** when running command:

`python3 server.py`

Full read out - 

> Traceback (most recent call last)
    File "server.py", line 350, in < module >
       ThreadedServer (host=const.ip, port=port)).listen()
     File "server.py", line 64, in _ _init_ _
       self.sock.bind((self.host, self.port))
 TypeError: an integer is required (got type NoneType)

Any suggestions on what I need to do to rectify this? Cheers

**Comment by naman108** [comment]
1. Can share your constants file

2. The way your beginning the server is deprecated as it doesnt allow for the use of datapackages you should begin with the following 
```
python3 run.py
```

**Comment by cherijakewell** [comment]
`python3 run.py`

Worked perfectly. Thanks very much!
