### ISSUE TITLE
Bind Address used with assumption that it's external

### ISSUE THREAD

**Issue by gregbuehler** [Tapawingo/FreeTakServer#51]
The IP address variable is defined at https://github.com/Tapawingo/FreeTakServer/blob/master/TAKfreeServer/constants.py#L15 is overloaded.

This is used both as the network component of the bind address (https://github.com/Tapawingo/FreeTakServer/blob/master/TAKfreeServer/httpServer.py#L255, https://github.com/Tapawingo/FreeTakServer/blob/master/TAKfreeServer/server.py#L58), and as the assumed external facing address to advertise (https://github.com/Tapawingo/FreeTakServer/blob/master/TAKfreeServer/httpServer.py#L147, https://github.com/Tapawingo/FreeTakServer/blob/master/TAKfreeServer/constants.py#L42).

If the externally accessible hostname or ip address is simplified it would enable running the server behind a proxy or within a docker container. Additionally it makes a bind address of 0.0.0.0 more feasible as the default.

**Comment by brothercorvo** [comment]
fixed in 0.8
