### ISSUE TITLE
0.8 dataport is hardcoded in two instances

### ISSUE THREAD

**Issue by Ole-Morten** [Tapawingo/FreeTakServer#55]
At two points it uses the const instead of the variable.

https://github.com/Tapawingo/FreeTakServer/blob/d09895503dad4f23bb9e962d95c577455bc29cc6/FreeTAKServer/controllers/DataPackageServer.py#L147

https://github.com/Tapawingo/FreeTakServer/blob/d09895503dad4f23bb9e962d95c577455bc29cc6/FreeTAKServer/controllers/DataPackageServer.py#L198

**Comment by brothercorvo** [comment]
fixed in 0.8.20
