### ISSUE TITLE
CreateLoggerController.py missing from install

### ISSUE THREAD

**Issue by nconder** [Tapawingo/FreeTakServer#60]
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-106-generic x86_64)

I followed the new install instructions on the home page.

I noticed that "CreateLoggerController.py" is missing from /usr/local/lib/python3.6/dist-packages/FreeTAKServer/controllers

Is this CreateLoggerController.py required or should it be included?

**Comment by naman108** [comment]
was this a pip installation?

**Comment by brothercorvo** [comment]
we need more info here

**Comment by brothercorvo** [comment]
will not fix

**Comment by nconder** [comment]
@naman108 yes this was a pip install.

**Comment by naman108** [comment]
Try to uninstall and install the newer version
